### ISSUE TITLE
Add information about managing projects in the Runtime UI

### ISSUE THREAD

**Issue by jwitz** [astronomer/cloud-docs#121]
**Request type:**

- [X] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [X] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

We have a lot of information about developing and managing local projects via the CLI, but very little about using the UI. Given the visual differences between Runtime and OSS Airflow UI, it makes sense to have a guide on everything you can do in the UI (with screenshots).

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by paolaperaza** [comment]
Gonna close this out @jwitz - let's handle this as part of the Airflow tutorial? The Airflow UI isn't drastically different between Runtime/otherwise just yet.
