### ISSUE TITLE
Create a dedicated "Troubleshoot" doc

### ISSUE THREAD

**Issue by jwitz** [astronomer/cloud-docs#141]
**Request type:**

- [X] **New document:**: Add the `docs-content` label to this issue.
- [] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [X] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:** Gen2 has some of the same weird behavior as Gen1. For a while, this was documented only in forum posts and small notes scattered throughout our docs. We should have a dedicated doc on the new site which compiles all of these issues and solutions. For example:

- Memory req's: https://forum.astronomer.io/t/airflow-ui-doent-work-on-localhost-after-astro-dev-start/1392
- Buildkit not supported error

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by paolaperaza** [comment]
All done - https://docs.astronomer.io/test-and-troubleshoot-locally

Will iterate on this over time.
